### ISSUE TITLE
v0.6.1 not compile for armv7 (ARM EABI support is required)

### ISSUE THREAD

**Issue by alexanderzhigulich** [LiquidPlayer/LiquidCore#100]
Hello!

Just cannot compile for **armv7** on latest **v0.6.1** from cocoapods.
Here is the error message **ARM EABI support is required**

Environment:
XCode Version 10.2.1 (10E1001).

If you'll need more info about error I will try to provide you one.

Thank you!

**Comment by ericwlange** [comment]
I'm pretty sure Apple has dropped support for 32-bit architectures in the latest SDK: https://arstechnica.com/gadgets/2017/04/what-the-death-of-32-bit-ios-could-mean-for-apples-hardware-and-software/

All phone from the iPhone 5s are arm64

Please correct me if I am wrong.  There is not a lot of information floating around.

**Comment by ericwlange** [comment]
Closing unless there is more information to act on.
