### ISSUE TITLE
64 bit support

### ISSUE THREAD

**Issue by kalokiston** [LiquidPlayer/LiquidCore#105]
It looks like android will require 64 bit native binaries by August 1st. Will LiquidCore support that?

**Comment by ericwlange** [comment]
LiquidCore has had native support for 64-bit devices optionally since version 0.4.4 and by default since 0.5.0.

**Comment by kalokiston** [comment]
Ok, thanks. That is good to know!

This is a really awesome and useful project btw. This is the best way I can see of running JS code on Android outside of a WebView, and that is a pretty amazing thing IMO.
