### ISSUE TITLE
Using `LiquidCore` in an Android app adds 27MB

### ISSUE THREAD

**Issue by capezzbr** [LiquidPlayer/LiquidCore#106]
Using `LiquidCore` in an Android app adds 27MB, is there a way to make the final apk smaller?

**Comment by ericwlange** [comment]
Hi Bruno, you must use APK splits to reduce the file size.  See [comment in this issue](https://github.com/LiquidPlayer/LiquidCore/issues/80#issuecomment-461786632).

**Comment by capezzbr** [comment]
Hey @ericwlange that is a great solution, thanks! 👍
