### ISSUE TITLE
ARM EABI support is required. v.0.6.1

### ISSUE THREAD

**Issue by DmitryM9** [LiquidPlayer/LiquidCore#107]
I'm trying to build a build for 64 bit architectures
Compilation crashes with ARM EABI support is required.
Here in this place
`// ARM EABI is required.
#if defined(__arm__) && !defined(__ARM_EABI__)
#error ARM EABI support is required.
#endif`

Here was no solution to a similar issue. https://github.com/LiquidPlayer/LiquidCore/issues/100

**Comment by ericwlange** [comment]
Can you give more details?  Which file, etc.  The error log would be helpful.  Thanks.

**Comment by DmitryM9** [comment]
I found a solution to this problem.
Need remove the lines arm7 and arm7s in the module assembly settings
![image](https://user-images.githubusercontent.com/29881776/58412604-7560f080-807f-11e9-867c-679905dd39f0.png)
