### ISSUE TITLE
axios requests for ios

### ISSUE THREAD

**Issue by DmitryM9** [LiquidPlayer/LiquidCore#113]
Hi. 
Post request via axios on ios sends invalid data to the server.  on android or node sends the data perfectly. 

**request from node**
![IMG_20190531_170955](https://user-images.githubusercontent.com/29881776/58711327-f6ddb900-83c6-11e9-9fc2-6a20918bb805.jpg)

**request from ios **
![IMG_20190531_171052](https://user-images.githubusercontent.com/29881776/58711368-17a60e80-83c7-11e9-931e-436f81f0942f.jpg)

**Comment by ericwlange** [comment]
Steps to reproduce?

Thanks for exercising the iOS code -- I don't think it has been properly stress-tested enough to this point.  The V82JSC layer is very tricky.

**Comment by DmitryM9** [comment]
No problems. Any post request on axios. For example:
`import * as axios from 'axios';

const data = JSON.stringify({
  todo: 'Buy the milk'
})
var axiossss = axios.create({
  baseURL: "https://enwau268cbyb.x.pipedream.net/",
  headers: {"Content-Type": 'application/json'},
});

axiossss.interceptors.request.use((request) => {
  console.log('Starting Request', request);
  return request;
});
axiossss.interceptors.response.use((response) => {
  console.log(`-------request_data--------\n${ JSON.stringify(response) }`);
  console.log(`-------status--------\n${ response.status }`);
  return response;
}, (error) => {
  console.log(`-------error_RequestClient--------\n${ error }`);
  if (error.response) {
    console.log(
      `-------error_RequestClient response--------\n${ JSON.stringify(error.response) }`
    );
  }
  return Promise.reject(error);
});
axiossss.post("", data);`

Run as microservices

**Comment by DmitryM9** [comment]
I also tried to make a request through the node API and request - everything works fine on ios

**Comment by ericwlange** [comment]
I was able to sucessfully use axios with v 0.7.2 on both iOS and Android.  Closing.  Please re-open if issue not resolved.
