### ISSUE TITLE
How can I call JavaScript functions in a JavaScript library?

### ISSUE THREAD

**Issue by paulobuchsbaum** [LiquidPlayer/LiquidCore#114]
Hi, 
I'm a colaborator in `MathJs` project, and I would like to use it in an app.  I'm developing for _Android_ with `LiquidCore`. The minified code in _JavaScript_  is in [math.min.js](https://unpkg.com/mathjs@6.0.2/dist/math.min.js). It seems to me that `MicroService` feature can help me, but I don't know how.  

`MathJs` works well in normal browsers:

```
<script src="./js/math.min.js">
  var sim = math.parser();
 document.getElementById("math").innerHTML = "love " + sim.eval('atan2(3, -3) * 2  / pi');
</script>

```
My target is call _JavaScript_  functions from `math.min.js` (or some compiled version) from _JavaScript_ code pieces, like the first example (that works for me)  in [Android LiquidCore Doc](https://github.com/LiquidPlayer/LiquidCore/tree/master/LiquidCoreAndroid) in  using `JSContext`.

What can I do?

**Comment by ericwlange** [comment]
Assuming `mathjs` is a pure javascript implementation that does not depend on the browser or node, you can use it directly on Android.

```java
JSContext context = new JSContext();
final String mathjs = /* math.min.js loaded into a String */;
context.evaluateScript(mathjs);
JSFunction eval = context.evaluateScript("math.parser().eval").toFunction();

// Now you can use `eval()` from Java
String math = "love " + eval.call(null, "atan2(3, -3) * 2  / pi").toString();
Log.d("mathjs", math);
```

On iOS, you should be able to do basically the same with the JavaScriptCore API.

If, however, it requires the node.js runtime, then you have to use a `MicroService`.

(note, the above is untested, so may contain bugs)

**Comment by paulobuchsbaum** [comment]
Thanks for your prompt answer, @ericwlange 

I'm programming my app in _Kotlin_. 
No problem because _Java_ and _Kotlin_ are fully interoperable. 
So I've put `math.min.js` in a _Asset_ in _Android Studio_.

```
val context = JSContext()
     // read the js file in Asset folder
val mathjs = this.assets.open("math.min.js").bufferedReader().use{it.readText()}  
context.evaluateScript(mathjs);    
val eval = context.evaluateScript("math.parser().eval").toFunction();  
 val result = "love " + eval.call(null, "atan2(3, -3) * 2  / pi").toString()  //  exception

```
However, it gave me a error when I've tried run my _JavaScript_ function.
The message is:

```
Caused by: TypeError: Cannot read property 'evaluate' of null
        at org.liquidplayer.javascript.JSFunction.apply(JSFunction.java:416)
```

The source code in `JSFunction.java` is 
```
public JSValue call(final JSObject thiz, final Object ... args) {
        return apply(thiz,args);     // Pass here (377)
   }
...
public JSValue apply(final JSObject thiz, final Object [] args) {
        try {
            return new JSValue(JNI().callAsFunction(
                    (thiz == null) ? null : thiz.JNI(), argsToValueRefs(args)), context);
        } catch (JNIJSException excp) {
            context.throwJSException(             // and gives an error here (416)
                    new JSException(new JSValue(excp.exception,context)));
            return new JSValue(context);
        }
    }

```
I tried to see Java code but I have  no hint.

When this feature is working it would be very interesting for the community to include in the documentation the feature to use functions and methods of  _JavaScript_ library, with `tofunction()` and `eval.call()`

**Comment by ericwlange** [comment]
The `TypeError` is coming from JavaScript.

The best way I have found to debug these things:

```
$ node
> let mathjs = String(fs.readFileSync('./math.min.js'))
undefined
> eval(mathjs)
true
> var e = math.parser().eval
undefined
> e("atan2(3, -3) * 2  / pi")
Warning: Method Parser.eval is renamed to Parser.evaluate. Please use the new method name.
TypeError: Cannot read property 'evaluate' of undefined
    at r.eval (eval at <anonymous> (repl:1:1), <anonymous>:55:343325)
> math.parser().eval("atan2(3, -3) * 2  / pi")
1.5
```

So the issue was that it didn't like that we grabbed the `eval` function and called it directly.  That's because it is expecting the `this` value to be the `parser`, and instead it was `null`.  So instead:

```kotlin
val parser = context.evaluateScript("math.parser()").toObject();
val eval = parser.property("eval").toFunction();
val result = "love " + eval.call(parser, "atan2(3, -3) * 2  / pi").toString();
```
In the `JSObject.call()` function, the first parameter is `this`.  We need to set it to the parser instead of `null`.

The JavaDoc for the API can be found here: https://liquidplayer.github.io/LiquidCoreAndroid/0.6.1/

**Comment by paulobuchsbaum** [comment]
Oh, thanks a lot.  It works like a charm. By the way, it's 1.5.

**Comment by ericwlange** [comment]
@paulobuchsbaum Yes, I discovered that in my node example above. :)

Glad it is working!
