### ISSUE TITLE
adapt and use npm packages

### ISSUE THREAD

**Issue by adlucio87** [LiquidPlayer/LiquidCore#116]
Hi,

I have done a flutter application and i like using your library:
https://pub.dev/packages/flutter_liquidcore

i like to use this npm packages in my code:
https://github.com/hakatashi/kindlegen

Do you think it could be work?

Can you adapt this npm packages for me. I don't understand how to do this.
Can you explain how can then add packages in my app.

Thanks
Andrea

**Comment by ericwlange** [comment]
Hi @adlucio87 ,

Kindlegen is a binary application and this npm package only provides a wrapper that spawns the binary in another process.  See `install.ls`:

```ls
require! {
  download
}

bin-url = switch process.platform
  | \darwin => 'https://kindlegen.s3.amazonaws.com/KindleGen_Mac_i386_v2_9.zip'
  | \linux => 'https://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz'
  | \win32 => 'https://kindlegen.s3.amazonaws.com/kindlegen_win32_v2_9.zip'
  | otherwise => throw new Error 'Unsupported platform'

download bin-url, \bin, {+extract} .then -> console.log 'Download completed'
```

This won't work on either Android or iOS unless you have the source code, and then perhaps it could be ported.

**Comment by adlucio87** [comment]
Thank you for your replay. 
I was hoping it was possible, I didn't think it was a wraper but a porting.
I believe that i have no alternative and wrap it on a linux container or a server and then expose api.
