### ISSUE TITLE
Building LiquidCore iOS Framework

### ISSUE THREAD

**Issue by hansengj** [LiquidPlayer/LiquidCore#118]
Running latest macOS Mojave (10.14.5), Xcode (10.2.1); installed latest CocoaPods. Build fails do to a missing file. Terminal output:
$ pod lib lint
 -> LiquidCore (0.6.2)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  /Development/Javascript Code/LiquidCore/deps/node-8.9.3/deps/v8/src/libplatform/worker-thread.cc:5:10: fatal error: 'src/libplatform/worker-thread.h' file not found

[!] LiquidCore did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.

**Comment by hansengj** [comment]
Note: The file worker-thread.h does exists with proper read permissions. Why does the build script fail to recognize it?

**Comment by ericwlange** [comment]
I haven't been able to reproduce this.  What are the contents of your `Podfile`?

**Comment by hansengj** [comment]
Hi Eric,

Thank you for your response.

I downloaded LiquidCode, which came with a LiquidCore.podspec file (attached). I cd to the LiquidCore directory and execute, as instructed, “pod lib lint” which gives the missing worker-thread.h file error.

If I do a do a —no-clean, is there anything from the pods workspace you want to see?

I appreciate LiquidCore has a Swift API. It greatly simplifies my using LCProcess since my iOS app is coded entirely in Swift.

Thanks,
Gil

**Comment by ericwlange** [comment]
Can you try updating XCode to make sure you are using the latest?

I am using XCode 10.3, OSX 10.14.5, Cocoapods 1.7.5

I am still not able to reproduce this error.

```bash
Erics-MacBook-Pro:LiquidCore $ pod lib lint

 -> LiquidCore (0.6.2)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description

LiquidCore passed validation.

Erics-MacBook-Pro:LiquidCore $ pod --version
1.7.5

Erics-MacBook-Pro:LiquidCore $ xcodebuild -version
Xcode 10.3
Build version 10G8

Erics-MacBook-Pro:LiquidCore $ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.5 (18F132)
      Kernel Version: Darwin 18.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Eric’s MacBook Pro
      User Name: *****
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 11 days 17:37

```

**Comment by hansengj** [comment]
When I sent you the error, I was running the latest version of macOS, Xcode and Cocoapods. Since then I’ve upgraded macOS to 10.14.6 and Xcode to 10.3. The version of CocoaPods remains the same, 1.7.3. Trying to build the iOS framework still fails. Our only difference is the version of CocoaPods. I will upgrade to 1.7.5, try again and let you know.

gilbert-hansens-computer:LiquidCore hansengj$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.6 (18G84)
      Kernel Version: Darwin 18.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Gilbert Hansen’s Computer (2)
      User Name: Gil Hansen (hansengj)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 15:06

gilbert-hansens-computer:LiquidCore hansengj$ xcodebuild -version
Xcode 10.3
Build version 10G8
gilbert-hansens-computer:LiquidCore hansengj$ pod --version
1.7.3
gilbert-hansens-computer:LiquidCore hansengj$ pod lib lint

 -> LiquidCore (0.6.2)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  /Development/Javascript Code/LiquidCore/deps/node-8.9.3/deps/v8/src/libplatform/worker-thread.cc:5:10: fatal error: 'src/libplatform/worker-thread.h' file not found

**Comment by hansengj** [comment]
I upgraded Cocoapods to 1.7.5 and building the iOS framework still fails.The cause remains a mystery. Thanks for your help. When I find time to investigate deeper and ever track down the cause and resolve the error, I will let you know. I have to assume that if I am having this build issue, others are too.  —Gil

gilbert-hansens-computer:LiquidCore hansengj$ pod --version
1.7.5
gilbert-hansens-computer:LiquidCore hansengj$ pod lib lint

 -> LiquidCore (0.6.2)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  /Development/Javascript Code/LiquidCore/deps/node-8.9.3/deps/v8/src/libplatform/worker-thread.cc:5:10: fatal error: 'src/libplatform/worker-thread.h' file not found

[!] LiquidCore did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
gilbert-hansens-computer:LiquidCore hansengj$

**Comment by ericwlange** [comment]
I'm just grasping at straws here, because this is hard to debug when I can't break it, but try adding:

```ruby
   "deps/node-8.9.3",
```

under

```ruby
s.preserve_paths = [
```

in your `LiquidCore.podspec` and let me know if that changes anything?

You can also try adding:

```ruby
          "$(PODS_TARGET_SRCROOT)/deps/node-8.9.3",
```

under

```ruby
      :HEADER_SEARCH_PATHS => [
```

**Comment by hansengj** [comment]
Eric,

Thanks for giving this some thought and your suggestions. I’ll take any straw if it is paper and not plastic.😀

I inserted  the text you specified in the LiquidCode.podspec one at a time. Unfortunately both builds failed the same way.

As you know, there are 2 node-8.8.3 folders in: LiquidCode/LiquidCoreiOS/LiquideCode/ and LiquidCore/deps/

I am going to download the iOS source again and try to build it. Another idea is to try building the framework on my older iMac running the last released version of High Sierra. This would rule out a difference in the 2 machine’s environment.

Will let you know.

Thanks,
Gil
