### ISSUE TITLE
How to make data persistent in two MicroService call ?

### ISSUE THREAD

**Issue by Pooja16Fartyal** [LiquidPlayer/LiquidCore#119]
Is there any way to persistent the data between two different MicroServices call ?

I want to make the data persistent by holding it in the variable but when a new MicroService occurs it refresh the variable and not keep the data persistent.

Help me on how to implement this caching mechanism in liquid.bundle file created by liquidcore?

**Comment by Pooja16Fartyal** [comment]
Hey @ericwlange 

Could you please help me in this issue?

Thanks!

**Comment by ericwlange** [comment]
Yes, you can use the filesystem.

If you want to store data that persists across microservice instances, you can do something like:

```javascript
const fs = require('fs')
const filename = '/home/local/persistentData.json'

function save(persistentData)
{
    fs.writeFile(filename, JSON.stringify(persistentData))
}

function load()
{
  return new Promise((resolve,reject)=>{
    fs.readFile(filename, (err,data) => {
      if (err) reject(err)
      else resolve(JSON.parse(data))
    })
  })
}
```

You can see the [filesystem documentation here](https://github.com/LiquidPlayer/LiquidCore/wiki/LiquidCore-File-System).

**Comment by Pooja16Fartyal** [comment]
Hey @ericwlange 

Thanks for your response.

But I want to know that Is there any way to read/write the file inside the bundle rather than keeping that file in native?

**Comment by ericwlange** [comment]
Not sure I understand the use case, but no.  The contents of the bundle are immutable.
