### ISSUE TITLE
Native Node modules -- SocketIO Server?

### ISSUE THREAD

**Issue by pdulapalli** [LiquidPlayer/LiquidCore#123]
I am attempting to use the `socket.io` module, version 1.3.7, and was wondering if the native binaries for this have been precompiled for LiquidCore?

-Thanks!

**Comment by ericwlange** [comment]
Is there a reason you have to use 1.3.7?  The latest version (2.2.0) is pure javascript with no native module dependencies.

**Comment by pdulapalli** [comment]
We have Socket IO clients that are still on the older 1.x versions, and may be unable to connect to a 2.x Socket IO server. https://github.com/socketio/socket.io/issues/3007

At this time, it's very difficult for us to upgrade the clients we have deployed, so we have to stick with the older Socket IO server as well, unfortunately. 

Would you mind outlining the procedure to compile that library for LiquidCore?

**Comment by ericwlange** [comment]
Which native modules are required for socket.io 1.3.7?

**Comment by pdulapalli** [comment]
These are the native modules it depends on:
1. `bufferutil@1.2.1` ---> `bufferutil.node`
2. `utf-8-validate@1.2.2` ---> `validation.node`

**Comment by ericwlange** [comment]
These should be _relatively_ straightforward.

Take a look at my mods in [`node-sqlite3`](https://github.com/LiquidPlayer/node-sqlite3) as a guide.

Pay particular attention to:
* The `liquidcore-addon` property in [`package.json`](https://github.com/LiquidPlayer/node-sqlite3/blob/master/package.json)
* The [`liquidcore`](https://github.com/LiquidPlayer/node-sqlite3/tree/master/liquidcore) directory

iOS is really straightforward.  You just need to create a podspec (see ['node-sqlite3.podspec'](https://github.com/LiquidPlayer/node-sqlite3/blob/master/node-sqlite3.podspec)) that replaces what `node-gyp` does.  You also need to register the plugin (see ['register.mm`)(https://github.com/LiquidPlayer/node-sqlite3/blob/master/liquidcore/ios/register.mm)) and include it in your podspec.

Android is slightly more complex.  You would create a new C++ library project in Android studio, and then include the C++ files in [`CMakeLists.txt`](https://github.com/LiquidPlayer/node-sqlite3/blob/master/liquidcore/node-sqlite3/src/main/cpp/CMakeLists.txt).  You have to do a little dance to get gradle to extract the appropriate headers.  See my comment [here](https://github.com/LiquidPlayer/LiquidCore/issues/52#issuecomment-504058021).  Registration is done like [this](https://github.com/LiquidPlayer/node-sqlite3/blob/master/liquidcore/node-sqlite3/src/main/java/org/liquidplayer/addon/NodeSqlite3.java).  With Android, the package and name of the class is important.  It must be in package `org.liquidplayer.addon` and the class must be named based on what the node file is called.  So in the case of `bufferutil.node`, the class should be `org.liquidplayer.addon.Bufferutil`.  See the [addon documentation](https://liquidplayer.github.io/LiquidCoreAndroid/0.6.2/org/liquidplayer/service/AddOn.html) for more info.

I want to simplify this process dramatically, but it will take some time to figure out a better way.

The four examples I've created so far are:

[`node-sqlite3`](https://github.com/LiquidPlayer/node-sqlite3)
[`ReactNativeSurface`](https://github.com/LiquidPlayer/node-sqlite3) (Ignore the README, it is out of date)
[`caraml-core`](https://github.com/LiquidPlayer/caraml-core)
[`caraml-console`](https://github.com/LiquidPlayer/caraml-console)
