### ISSUE TITLE
Migrate from dcendents

### ISSUE THREAD

**Issue by BugsBunnyBR** [LiquidPlayer/LiquidCore#128]
The project https://github.com/dcendents/android-maven-gradle-plugin
is no longer updated and recommends to migrate to another project.
The current gradle version in this project is 4.10, and that plugin is not updated to support gradle above 4.6.

The suggestion is to migrate to 
https://github.com/sky-uk/gradle-maven-plugin

But I am not well versed in maven, so I will not be able to create a PR to this.

Thanks.

**Comment by consp1racy** [comment]
Or wait for Android Gradle Plugin 3.6 (currently in beta) which has publishing baked in.

**Comment by ericwlange** [comment]
I am going to move publishing to [`Github Packages`](https://help.github.com/en/github/managing-packages-with-github-packages) and `npm` for 0.7.0 and future releases.  JitPack is very poorly supported.

**Comment by ericwlange** [comment]
Quick update on Github Packages: this feature does not work without authentication even for just downloading (see [discussion here](https://github.community/t5/GitHub-API-Development-and/Download-from-Github-Package-Registry-without-authentication/m-p/35501#M3312)), which makes it pretty useless for an open source project.  I need to figure out another solution.

**Comment by ericwlange** [comment]
A workaround has been implemented for 0.7.x until either github packages or android gradle plugin support anonymous downloads.
