### ISSUE TITLE
Debug Logging from JS?

### ISSUE THREAD

**Issue by charles-b-stb** [LiquidPlayer/LiquidCore#13]
Is there an existing of planned interface to pass logging information from javascript back to the android log so we can see it in logcat?

Its difficult to trace errors that cross the javascript/java divide without some sort of shared logging.

**Comment by se-bastiaan** [comment]
I had exactly the same issue. You an easily add a JSObject to your JSContext that implements `console.log`.

```
JSObject console = new JSObject(jsContext);
console.property("log", new JSFunction(jsContext, "log") {
    public void log(JSValue message) {
       Timber.d("JS Console log: %s", message.toJSON());
    }
});
jsContext.property("console", console);
```

**Comment by ericwlange** [comment]
Yes, that is the correct way to do this.

If you use a node [`Process`](https://liquidplayer.github.io/LiquidCoreAndroid/org/liquidplayer/node/Process.html), you get `console.log` for free.  But it may be more overhead than you need.

**Comment by charles-b-stb** [comment]
This looks useful. Thanks.

This only works in liquidcore, right? It wasn't implemented to work in AndroidJSCore?

**Comment by se-bastiaan** [comment]
I wrote this specifically for LiquidCore, but it may work with AndroidJSCore.
Although, I'd recommend you to use LiquidCore. Since it offers the same functionality (and more) and AndroidJSCore is not supported anymore.

**Comment by ericwlange** [comment]
It will work in AndroidJSCore too.  But LiquidCore is where it's at.
