### ISSUE TITLE
Memory leaks happen on websockets

### ISSUE THREAD

**Issue by SkripnD** [LiquidPlayer/LiquidCore#131]
When we're using LiquidCore for WebSocket works in iOS background queue, after few minutes (usually, about 5-10 minutes) some memory leaks happens and we got memory error.

I've tried your iOS example and there similar situation.

**Comment by ericwlange** [comment]
@SkripnD Can you provide a sample project that demonstrates the issue?  Thanks.

**Comment by ericwlange** [comment]
A bunch of iOS memory leaks were fixed in 0.7.2.  This was probably one.  Please re-open if this still happens with the latest.
