### ISSUE TITLE
x86_64 and arm64-v8a not created for 64 bit devices

### ISSUE THREAD

**Issue by Reegan01** [LiquidPlayer/LiquidCore#144]
Hi, 

I have got this Error from Play store while I uploading my app with this library. Kindly help to resolve this. I'm using v 0.3.1 of your lib.  

implementation `'com.github.LiquidPlayer:LiquidCore:0.3.1'`

![App releases - Linga Kiosk - Google Play Console](https://user-images.githubusercontent.com/7336944/70714389-093d9580-1d0e-11ea-9a90-e75c19c7ca54.png)

**Comment by ericwlange** [comment]
@Reegan01  Why are you using a version that is more than 2 years old?  There have been 337 commits to master since then, one of which is default 64-bit support.
