### ISSUE TITLE
Microservice clear listener

### ISSUE THREAD

**Issue by DhivinX** [LiquidPlayer/LiquidCore#148]
How to clear listener in NodeJS (MicroService) of LiquidCore.on()?
In java it is possible by service.removeEventListener(), how do it in javascript node?

Can't see method LiquidCore.off() like in socket.io.

**Comment by ericwlange** [comment]
The `LiquidCore` javascript object is just an [`events`](https://nodejs.org/docs/latest-v8.x/api/events.html) object.  You can call [`LiquidCore.removeListener()`](https://nodejs.org/docs/latest-v8.x/api/events.html#events_event_removelistener).

**Comment by DhivinX** [comment]
Thanks this is it!
