### ISSUE TITLE
Android Jitpack builds failing

### ISSUE THREAD

**Issue by kaneelyster** [LiquidPlayer/LiquidCore#152]
Refer to https://jitpack.io/#LiquidPlayer/LiquidCore

From 0.70 onward the Android Jitpack builds are failing, causing gradle sync failures when trying to use 0.7.0+ in my project.

The alternative of using `% npm i -g liquidcore-cli` yields the same gradle sync failures.

**Comment by ericwlange** [comment]
Jitpack has been deprecated from 0.7.0+ because it requires a deprecated gradle plugin (see #128).  Please remove the `implementation` line for jitpack.  The `input.gradle` file manages downloading the artifacts.

**Comment by kaneelyster** [comment]
@ericwlange Apologies for sounding dumb, but where do I find the `implementation` line for jitpack? Are you referring to `maven { url 'https://jitpack.io' }` under my project's top-level build.gradle?

What I have tried is to remove `implementation 'com.github.LiquidPlayer:LiquidCore:0.7.0'` from my app-level `build.gradle` to no avail. Changing liquidcore.build.gradle to use 0.6.2 works fine, but 0.7.0 fails.

**Comment by ericwlange** [comment]
Remove everything related to JitPack: both `maven { url 'https://jitpack.io' }` and `implementation 'com.github.LiquidPlayer:LiquidCore:0.7.0'`.

Jitpack is no longer supported with LiquidCore.

Instead, follow the installation instructions on either the main [README](https://github.com/LiquidPlayer/LiquidCore/blob/master/README.md) if you are using Node.js functionality or the updated [README](https://github.com/LiquidPlayer/LiquidCore/wiki/LiquidCore-as-a-Raw-JavaScript-engine-for-Android-(v.-0.7.0-)) for just using the JavaScript engine.

From now on (or until I find a better way), distribution is happening through `npm`, so you can't skip the `npm` setup steps.

**Comment by kaneelyster** [comment]
Thank you, that cleared it up.

I also had to add the following to the top-level `build.gradle`
```
buildscript {
    dependencies {
        classpath 'de.undercouch:gradle-download-task:1.2'
    }
}
ext {
    Download = de.undercouch.gradle.tasks.download.Download
    download = download
}
```

and this to the module's
```
apply plugin: 'de.undercouch.download'
```

to get the Gradle Download Task dependency working.

**Comment by ericwlange** [comment]
@kaneelyster Interesting -- I haven't needed to do that.  Let me investigate.  Thanks!  Glad you got it working.
