### ISSUE TITLE
Execution failed for task ':app:bundleLiquidCoreCode'.

### ISSUE THREAD

**Issue by Iyamu-J** [LiquidPlayer/LiquidCore#154]
This is what I am getting from Gradle;
```
* What went wrong:
Execution failed for task ':app:bundleLiquidCoreCode'.
> A problem occurred starting process 'command '/usr/bin/env''
```

I checked the liquidcore.build.gradle and there's a line `executable '/usr/bin/env'` which I feel might be the source of the error. Is there a way to resolve it?

**Comment by And42** [comment]
If you are on Windows, try replacing `executable '/usr/bin/env'` with `executable '<path_to_node.exe>'` and remove the first argument from `args [...]` so that gradle call node.exe directly

**Comment by ericwlange** [comment]
I do not have a Windows device.  If someone wants to submit a PR for this, I will happily merge it.  Please reopen if needed.
