### ISSUE TITLE
[Question] - Is there a version of this repo that exists for xamarin

### ISSUE THREAD

**Issue by DanielMcMahon** [LiquidPlayer/LiquidCore#176]
Hi, im curios to know is there a build that exists out there for xamarin?

Ive done a fair amount of searching and i cant find it at all. 
In work we use this library to query a js object on Xamarin Android, Is there any documentation how you would build it for Xamarin Android/Forms?

Many thanks

**Comment by ackava** [comment]
@DanielMcMahon I created Xamarin-v8 from this repository, https://github.com/web-atoms/xamarin-v8

**Comment by DanielMcMahon** [comment]
@ackava Are there any details docs for this ? I can see the read.me but not the Full documentation ... I appreciate there not be any or in the process of building. 

Many Thanks

**Comment by ackava** [comment]
There is no build needed, just import the nuget package and start using namespace Xamarin.Android.V8, I will update the doc.

**Comment by DanielMcMahon** [comment]
@ackava Thats great, Thank you !
