### ISSUE TITLE
Is it possible to reduce file size

### ISSUE THREAD

**Issue by martinspaeth** [LiquidPlayer/LiquidCore#23]
Hey,
me again, when building the app with the library included the download size (size of the packed apk) and the usage on device increase dramatically:

![image](https://cloud.githubusercontent.com/assets/4928482/24827024/5b890e06-1c43-11e7-8d50-ab381b4b1981.png)

Since we have to deal with small devices (from a memory perspective) every megabyte counts. Is there a way to reduce the usage of the native libraries?
I am not in to native libraries yet but may we could have a "common" library instead of increasing the size by 4 when including the native libs for every system architecture. 

If i can support in any way just let me know! 

Best regards 
Martin

**Comment by martinspaeth** [comment]
I just found an interesting blog post about that topic you might find interesting:
https://realm.io/news/reducing-apk-size-native-libraries/

We will tinker around with different apk files per architecture (also linked in the original article):
https://developer.android.com/studio/build/configure-apk-splits.html
I will keep you up to date about the progress on this our side!

**Comment by ericwlange** [comment]
Yeah, I [referenced that article](https://github.com/ericwlange/AndroidJSCore#frequently-asked-questions) in AndroidJSCore.

There is not much I can do with `libnode.so`.  It is what it is.  I stripped everything out of it that had any bulk (especially [ICU](http://site.icu-project.org/) which is a pig).  However, I have to say that I am surprised that `libliquidcore.so` is the same size.  It should be nowhere near that big.  I may have unintentionally left all the symbols in it.  I'll take a look at it.  That should reduce the size dramatically.

As you rightly note, if you are really concerned about APK size, you will need to do an APK split.  I had considered publishing separate libraries for each arch, plus one big one multi-arch one for those who aren't concerned about size, but I never really got around to it.

**Comment by martinspaeth** [comment]
No Worry the size of ibliquidcore.so is only the smallest one here (1.2 MB compared to lobnode.so 17.7 mb). 

We are currently using libliquidcore via gradle. 
To split the apk's i will have to include the library as described in
"Building the LiquidCore Android library"?

**Comment by ericwlange** [comment]
Maybe.  I haven't actually tried it.  It may be possible to do the APK split from the app itself.  Android Studio may be smart enough to ignore anything not related to the ABI.

**Comment by martinspaeth** [comment]
Ok we will check it out and keep you up to date! thank you!

**Comment by ericwlange** [comment]
Just came across this when working with React Native: https://developer.android.com/studio/build/configure-apk-splits.html

This is a step-by-step how-to from Google.

**Comment by ericwlange** [comment]
Update on this:  Version 0.3.0 reduces the size of the library by half by removing explicit support for 64-bit architectures (they can use the 32-bit versions without issue), and stripping out the debugging symbols.  So the current aar is ~15MB.  My goal is to get it under 10MB.  I think there several other opportunities for reduction.

**Comment by ericwlange** [comment]
I was able to squeeze out another ~1.5MB by re-using the built-in Android SQLite implementation, rather than compiling sqlite3.c into the project.  The footprint (not rolled into a release yet) is now at 13.3MB.  Running out of opportunities for reduction, though.

**Comment by ericwlange** [comment]
This is resolved in the new release, [0.4.0](https://github.com/LiquidPlayer/LiquidCore/releases/tag/0.4.0).  To reduce further, be sure to enable ABI splits in your `build.gradle`.
