### ISSUE TITLE
Typo in readme's gradle section

### ISSUE THREAD

**Issue by martinspaeth** [LiquidPlayer/LiquidCore#24]
```
dependencies {
    ...
    compile 'com.github.LiquidPlayer.LiquidCore:0.2.2'
}
```

should read like:
```

dependencies {
    ...
    compile 'com.github.liquidplayer.LiquidCore:0.2.2'
}
```

**Comment by ericwlange** [comment]
Are you sure about that?

See: https://jitpack.io/#LiquidPlayer/LiquidCore/0.2.2

It is also like this in the example, which builds correctly: https://github.com/LiquidPlayer/Examples/blob/master/HelloWorld/app/build.gradle

**Comment by martinspaeth** [comment]
It seems there where some caching problems in our gradle build script in combination with Android studio.

The original 'com.github.LiquidPlayer.LiquidCore:0.2.2' was right so!
