### ISSUE TITLE
App crashes due to too many open files

### ISSUE THREAD

**Issue by SKrPl** [LiquidPlayer/LiquidCore#26]
The last segment of [log](https://pastebin.ubuntu.com/24937456/) when app crashes.
Complete [log](https://pastebin.ubuntu.com/24937537/) of the app runtime.

Background of App:
* Every 8 seconds from a Fragment, 5 requests are sent to a microservice (5 new threads are opened for this).
* The received response from the 5 requests (5 threads) within a period of 8 seconds are collected and displayed in UI.
* Apps runs fine for around 11 minutes, but then it crashes with the following error:
``` 06-24 07:33:04.513 24171-1946/org.loklak.android.wok E/art: ashmem_create_region failed for 'indirect ref table': Too many open files```.

**Comment by ericwlange** [comment]
Interesting.  Are you doing any file manipulation inside the microservice?

**Comment by SKrPl** [comment]
I am sending a network request using microservice then parsing it and emitting the result back to Java.

**Comment by SKrPl** [comment]
@ericwlange Here is how I am using the microservice,  [`getScrapedTweets`](https://github.com/SKrPl/loklak_wok_android/blob/defec927f019c0cb6f17cf08bafa9204e5c4b120/app/src/main/java/org/loklak/android/ui/fragment/TweetHarvestingFragment.java#L193-L209) method receives a `query`, it then sends this query to *Microservice*, microservice sends a GET request, once the result of GET request is obtained by microservice, the result is emitted back to Fragment.

This process is repeated in method [`dispalyAndPostScrapedData`](https://github.com/SKrPl/loklak_wok_android/blob/defec927f019c0cb6f17cf08bafa9204e5c4b120/app/src/main/java/org/loklak/android/ui/fragment/TweetHarvestingFragment.java#L261-L268) with a time gap of 4 seconds. The app runs for around 20 minutes, and then crashes.

**Comment by ericwlange** [comment]
Thanks.  I will see if I can replicate this faster with some simpler test.  This just sounds like I didn't close something somewhere.  But it is going to take me some time to dedicate effort to this project.  I started a new job recently and am slammed.

**Comment by ericwlange** [comment]
Have made a ton of changes that resolve a bunch of reliability issues.  So, closing this.  Please re-open if it re-occurs.
