### ISSUE TITLE
How to init Microservice with local node module and dependencies?

### ISSUE THREAD

**Issue by ilyamuromets** [LiquidPlayer/LiquidCore#28]
Is it possible to start **Microservice** with local node module with dependencies? For example: I have **app.js** file in raw directory with the following: `var express = require('express');`
How to include express module in project?

**Comment by ilyamuromets** [comment]
I have found a solution: just place node's module directory into assets/node_modules.

**Comment by twhit093** [comment]
@ilyamuromets what's the full path to the assets folder? app/assets/node_modules?

**Comment by twhit093** [comment]
Nevermind, I think it should be app/build/intermediates/assets/debug/node_modules/sqlite3

**Comment by ericwlange** [comment]
@ilyamuromets - This is kind of an ugly solution.  The goal of LiquidCore is portability between apps, so copying something to your local assets folder defeats the ability for a developer to be able to be able to simply launch your micro service in another app.  Again, it is supposed to be kind of an `<iframe>` for native apps.

The right way to do this is to use [`liquidserver`](https://www.npmjs.com/package/liquidserver).  `liquidserver` is designed to walk through all `require` statements and roll the code into a single file.  It uses [`browserify`](http://browserify.org/) to do this.  You can use `browserify` directly if you'd like, but you have to make sure you get the command-line options right.  You can see the required options in [`index.js':191`](https://github.com/LiquidPlayer/LiquidServer/blob/master/index.js).

Copying into assets is unscalable in the long run.
