### ISSUE TITLE
How to set property from js into java object?

### ISSUE THREAD

**Issue by ilyamuromets** [LiquidPlayer/LiquidCore#31]
From java to js works fine:
```
class Test extends JSObject implements TestImpl {
  @jsexport public Property<JSValue> x;

  Test() {
    x.set(new JSValue(getContext(), "123"));
  }
}
```
If now I input in js `test.x = "test";` nothing will happen. `x` in java will be equal `123`.

**Comment by ericwlange** [comment]
Interesting, that sounds like a bug.

Alternatively, you could rewrite as follows:

```java
class Test extends JSObject implements TestImpl {

  Test() {
    property("x", "123");
  }
}
```

Then it should work.

**Comment by ericwlange** [comment]
I can't replicate a problem.  I think you may have just missed setting the context.  It should be:

```java
class Test extends JSObject implements TestImpl {

  Test(JSContext context) {
    super(context)
    property("x", "123");
  }
}
```

That way it works as expected.
