### ISSUE TITLE
How to call js's garbage collector to determine that native objects are destroyed?

### ISSUE THREAD

**Issue by ilyamuromets** [LiquidPlayer/LiquidCore#32]
I have found that native objects are destroyed only if I set null on a JSContext's reference and manually init GC from IDE.
I want to check that js's objects without references was destroyed.

**Comment by ericwlange** [comment]
Unfortunately there is no way at this point to force garbage collection without rebuilding the library.  The function is exposed in the [JavaScriptCore shell implementation](https://github.com/LiquidPlayer/LiquidCore/blob/master/LiquidCoreAndroid/jni/JSC/JSC_JSBase.cpp#L108), but it is not exposed through JNI so it can't be called directly from Java.  It is trivial to do so, but would require some work on both the Java and C++ sides.
