### ISSUE TITLE
How to use Object defineProperty in javascriptcore for android

### ISSUE THREAD

**Issue by chrisbarry** [LiquidPlayer/LiquidCore#34]
I've asked the following question on stackoverflow, I was wondering if you could help.

https://stackoverflow.com/questions/45488933/how-to-use-object-defineproperty-in-javascriptcore-for-android

I'm really sorry for asking here, is there another way to ask questions such as this, or improve this method (Would asking the same question here be appropriate?)

Which docs are the best these days for looking something like this up?

**Comment by chrisbarry** [comment]
I think I might have found it on this page - https://github.com/ericwlange/AndroidJSCore/blob/master/examples/AndroidJSCoreExample/app/src/main/java/org/liquidplayer/androidjscoreexample/OwenMatthewsExample.java

**Comment by ericwlange** [comment]
I posted this to Stackoverflow as well.  Sorry for the delay.  I've been on other projects for a bit.

There is another way to do it that is not particularly well documented, but is far more elegant.  You can use the `@jsexport` attribute on a `JSObject`.

```java
    private class Foo extends JSObject {
        Foo(JSContext ctx) { super(ctx); }

        @jsexport(type = Integer.class)
        Property<Integer> x;

        @jsexport(type = String.class)
        Property<String>  y;

        @jsexport(attributes = JSPropertyAttributeReadOnly)
        Property<String> read_only;

        @SuppressWarnings("unused")
        @jsexport(attributes = JSPropertyAttributeReadOnly | JSPropertyAttributeDontDelete)
        int incr(int x) {
            return x+1;
        }
    }
```

Then you can use the getter/setter methods in both Java and Javascript:

```java
    Foo foo = new Foo(ctx);
    ctx.property("foo", foo);
    ctx.evaluateScript("foo.x = 5; foo.y = 'test';");
    assertEquals((Integer)5, foo.x.get());
    assertEquals("test", foo.y.get());
    foo.x.set(6);
    foo.y.set("test2");
    assertEquals(6, foo.property("x").toNumber().intValue());
    assertEquals("test2", foo.property("y").toString());
    assertEquals(6, ctx.evaluateScript("foo.x").toNumber().intValue());
    assertEquals("test2", 
        ctx.evaluateScript("foo.y").toString());
    ctx.evaluateScript("foo.x = 11");
    assertEquals((Integer)11, foo.x.get());
    assertEquals(21, 
        ctx.evaluateScript("foo.incr(20)").toNumber().intValue());

    foo.read_only.set("Ok!");
    assertEquals("Ok!", foo.read_only.get());
    foo.read_only.set("Not Ok!");
    assertEquals("Ok!", foo.read_only.get());
    ctx.evaluateScript("foo.read_only = 'boo';");
    assertEquals("Ok!", foo.read_only.get());
```
