### ISSUE TITLE
avc: denied error on network calls

### ISSUE THREAD

**Issue by StephenBrough** [LiquidPlayer/LiquidCore#35]
I'm running an emulator and have been trying to make network calls from Node using request and have also tried axios. So far I've run into these two issues with both:

`W/dcorehelloworld: type=1400 audit(0.0:59): avc: denied { ioctl } for path="/sys/kernel/debug/tracing/trace_marker" dev="debugfs" ino=3080 ioctlcmd=5451 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:debugfs_trace_marker:s0 tclass=file permissive=0`

`W/dcorehelloworld: type=1400 audit(0.0:60): avc: denied { ioctl } for path="socket:[181434]" dev="sockfs" ino=181434 ioctlcmd=5451 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0`

I've also tried this on a physical Nexus 6p and I'm not seeing the errors but none of my callbacks in Java are being called, so I'm assuming the request is not going through.

**Comment by bootstraponline** [comment]
maybe this is related:

> Further restrict socket ioctls available to apps

- https://android.googlesource.com/platform/external/sepolicy/+/556bb0f55324e8839d7b735a0de9bc31028e839e

**Comment by ericwlange** [comment]
Closing as this is not really a LiquidCore issue.
