### ISSUE TITLE
Promise doesn't work

### ISSUE THREAD

**Issue by ilyamuromets** [LiquidPlayer/LiquidCore#36]
I try to using Promise but nothing works out. The following code doesn't work:
```
var promise = new Promise(function(resolve, reject) {
    resolve(123);
});

promise.then(function(result) {
    console.log(result);
});
```
This code will work fine if I execute it in a browser.

**Comment by ilyamuromets** [comment]
I checked the above code in **JSContext** without running **Microservice** - works fine!!
What could be the problem?

**Comment by ilyamuromets** [comment]
I have found another interesting thing. If I kill process `process.exit(0);` then the promise function `resolve(123);` will be executed.

**Comment by ilyamuromets** [comment]
I have found problem. When I start **Microservice** I eval the code `setInterval(function(){}, 3600000);`
When I changed code to `setInterval(function(){}, 1000);` pomises have worked.

**Comment by ericwlange** [comment]
I find it shocking that `setInterval` would cause other events to block!  Let me see if that is the intended behavior.

**Comment by ericwlange** [comment]
Not sure what the issue was before, but I added a test for this and it is passing with no trouble now.  Closing.
