### ISSUE TITLE
invoke js methods from .js file

### ISSUE THREAD

**Issue by Yuliya-Kaleda** [LiquidPlayer/LiquidCore#38]
I am trying to find a way to invoke functions written in javascript and located in .js file on the server. Is there a way LiquidCore can work directly with .js file and its methods?

**Comment by Yuliya-Kaleda** [comment]
@ericwlange sorry for a bit vague question. I have a js file, which I need to load into JSContext. What is the right syntax to do that?

**Comment by ilyamuromets** [comment]
@Yuliya-Kaleda 
```
JSContext jsContext = new JSContext();
jsContext.evaluateScript(<your_script_contents_loaded_from_the_server>);
```
