### ISSUE TITLE
JNI ERROR: global weak reference table overflow

### ISSUE THREAD

**Issue by buddhirajapraksh** [LiquidPlayer/LiquidCore#45]
In my app I was running a rendering loop which was creating/destroying many JSValue objects. It quickly resulted into "global weak reference table overflow".  I fixed the issue with attached patch
[liquidcorepatch.log](https://github.com/LiquidPlayer/LiquidCore/files/1688187/liquidcorepatch.log)

**Comment by ericwlange** [comment]
This issue is a duplicate of #44 .  

Thanks for the patch -- I will evaluate it tonight!
