### ISSUE TITLE
Where can I download a precompiled .aar file

### ISSUE THREAD

**Issue by cdesewell** [LiquidPlayer/LiquidCore#54]
Hi all

I'm looking to bind this into a Xamarin package for an Android project I'm currently working on however Xamarin projects do not leverage gradle or other standard java/android build systems. Is there somewhere to download a compiled .aar of the engine?

**Comment by ericwlange** [comment]
Sure.  I think this will work (direct download from jitpack):
https://jitpack.io/com/github/LiquidPlayer/LiquidCore/0.4.6/LiquidCore-0.4.6.aar

**Comment by cdesewell** [comment]
Great thanks!
