### ISSUE TITLE
Unable to use external libraries while running raw js natively in Android

### ISSUE THREAD

**Issue by alphaguy4** [LiquidPlayer/LiquidCore#58]
Hi , i am using XMLHttpRequest library in my raw javascript which is natively running on an Android app.
It throws runtime error and  it say XMLHttpRequest not defined.

**Comment by ericwlange** [comment]
XMLHttpRequest is not part of the JavaScript runtime.  It is provided by the DOM (browser).  LiquidCore is not a browser, so that object does not exist natively.  You can, however, use the node.js runtime, which includes http capability.  If you insist on using XMLHttpRequest, you would need to use a polyfill.

**Comment by alphaguy4** [comment]
Thanks for the info @ericwlange .
Closing the issue!!

**Comment by alphaguy4** [comment]
Hi,
As mentioned in the README.md. <pre>A micro service is nothing more than an independent Node.js instance whose startup code is referenced by a URI</pre>
Is there a way to install other libraries which can be imported in the javascript file (say request libraries).

**Comment by ericwlange** [comment]
Yes.  If you read further down in the tutorial there is an example that requires the `bignumber.js` module to demonstrate how to include external node modules.

**Comment by alphaguy4** [comment]
Correct!! 
But that case is applied when you use and external machine to host a liquidserver on some specific port. I can easily install other libraries using npm and it will work smoothly.
What to do in the case when the <pre>services.js</pre> file is hosted locally in <pre>android.resource</pre> how to use <pre>bignumber.js</pre> in that file.

**Comment by ericwlange** [comment]
You can just take the file generated by liquidserver and copy it into your android resources and you don't need a server.

**Comment by alphaguy4** [comment]
Tell me if i am wrong but does it means every time i need a new module in my javascript i need to install it using npm on a machine and copy it back to my android.resource in my app ?

**Comment by ericwlange** [comment]
Yes.  But wouldn't you have to do that anyway if you wanted to change _anything_ in your javascript?

**Comment by alphaguy4** [comment]
Right!
ok thanks !! 👍
