### ISSUE TITLE
Unable to read a file using fs library [file not found Exception]

### ISSUE THREAD

**Issue by alphaguy4** [LiquidPlayer/LiquidCore#61]
Hi,
I am trying to read a file during the runtime of the script(`service.js`) as follows:
<pre>
const fs = require('fs')
LiquidCore.on( 'get', function() {
    var jsonObj = {}
    jsonObj = JSON.parse(fs.readFileSync('./file.json','utf-8'))
    LiquidCore.emit('post',jsonObj);
    process.exit(0)
})
</pre>
It app throws an error `File Not found`

while using require to load the file like below:
<pre>
LiquidCore.on( 'get', function() {
    var jsonObj
    jsonObj = require('./file.json')
    LiquidCore.emit('post',jsonObj);
    process.exit(0)
})
</pre>
It works fine.
What is the problem? 

PS :`file.json` is in same directory as `service.js`

**Comment by ericwlange** [comment]
try `fs.readFileSync('/home/module/file.json','utf-8')`.  The description of the file system is [here](https://github.com/LiquidPlayer/LiquidCore/wiki/LiquidCore-File-System).

**Comment by ericwlange** [comment]
If you want to read files from a server, you will have to implement reading them from a server using `request` (or any other http library).  `liquidserver` doesn't function as a general purpose file server.

**Comment by alphaguy4** [comment]
Thanks man!! problem solved .. appreciate it
