### ISSUE TITLE
Add reference to MIT license (to make that official)

### ISSUE THREAD

**Issue by aschrijver** [LiquidPlayer/LiquidCore#62]
Thanks for your cool project, and mentioning it on my SO investigation of [Viable options for running NodeJS on Android](https://stackoverflow.com/questions/45459909/viable-options-for-running-nodejs-on-android-aug-2017/).

As [you mentioned in your comment](https://stackoverflow.com/questions/45459909/viable-options-for-running-nodejs-on-android-aug-2017/52271587?noredirect=1#comment91498014_52271587), the project is effectively licensed under MIT license.

Would be great if you could make this explicit, by adding the license file in a way recognized by Github. Additional benefit is that a license-based search will also include your project more easily (MIT is most used in JS / NodeJS world, as you know)

**Comment by ericwlange** [comment]
This is now complete.
