### ISSUE TITLE
Abort script caught in infinite loop

### ISSUE THREAD

**Issue by Eliott** [LiquidPlayer/LiquidCore#65]
Is it possible to abort a script running in a separate thread that's caught in an infinite loop?

For example, how can I force the following thread to exit? Calling thread.interrupt() does nothing.

    Thread thread = new Thread
    (  new Runnable()
       {  @Override
          public void run()
          {  new JSContext().evaluateScript("while(true) true;");
          }
       }
    );

**Comment by ericwlange** [comment]
There isn't an exposed JNI method to do that, I'm afraid.  It can be achieved by calling [`Isolate::RequestInterrupt()`](https://v8docs.nodesource.com/node-8.11/d5/dda/classv8_1_1_isolate.html#a79301bfdebcc33f447be8dbefb23bf27) directly in V8, but you would have to add a JNI method to make that call from Java.

**Comment by Eliott** [comment]
Thank you. I have that working now. Is there anything else that needs to be done, like running garbage collection or any other clean up, or is it enough to just terminate?

**Comment by ericwlange** [comment]
It should be enough just to terminate.

**Comment by Eliott** [comment]
Thank you.
