### ISSUE TITLE
How to pass Custom Java object to LiquidCore

### ISSUE THREAD

**Issue by kashifgrocerkey** [LiquidPlayer/LiquidCore#66]
Hi I have a class Person as:

```
class Person {
@JsonProperty("Name")
String name;

@JsonProperty("Age")
int age;
}

I want to pass this into LiquidCore but i got exception unknown property 'Name' from underlying js function. But if i covert my 'Person' object into Map/HashMap using 'ObjectMapper' and then pass it to LiquidCore then it works fine but it has performance issues.

Please suggest any good way to pass Custom Java objects as well as List of to LiquidCore

**Comment by ericwlange** [comment]
The annotations are not well documented, but you can do it like this:

```java
public class Person extends JSObject {
    @jsexport(type = String.class)
    Property<String> name;

    @jsexport(type = Integer.class)
    Property<Integer> age;

    Person(JSContext ctx, String name, Integer age) {
        super(ctx);
        this.name.set(name);
        this.age.set(age);
    }
};
```

**Comment by kashifgrocerkey** [comment]
Thanks for your reply.

How can i add it with @JsonProperty ? Actually I get response from Web Api then serial it with @JsonProperty 

Can i do this?
`public class Person extends JSObject {
    @jsexport(type = String.class)
    @JsonProperty("Name")    
    Property<String> name;

    @jsexport(type = Integer.class)
    Property<Integer> age;

    Person(JSContext ctx, String name, Integer age) {
        super(ctx);
        this.name.set(name);
        this.age.set(age);
    }
};`

**Comment by ericwlange** [comment]
I don't know much about `@JsonProperty`, but if it is a JSON object you want to pass to LiquidCore, you can use [`JSON.parse()`](https://liquidplayer.github.io/LiquidCoreAndroid/0.5.0/org/liquidplayer/javascript/JSON.html#parse-org.liquidplayer.javascript.JSContext-java.lang.String-) like so:

```java
String myJSONString = "..."; // I assume you can get this from ObjectMapper
JSValue person = JSON.parse(jsContext, myJSONString);
```

But I am not sure if this is any different than what you originally did, so it may have similar performance issues.

**Comment by kashifgrocerkey** [comment]
Wow, thanks JSON.parse(jsContext, myJSONString) really helps alot for me and boost performance
