### ISSUE TITLE
How to create a promise object from java?

### ISSUE THREAD

**Issue by Tlaster** [LiquidPlayer/LiquidCore#69]
I want to create a promise object from java and call it from javascript like
```
const file = await readFileString('file.txt');
```
I'm using LiquidCore as Native Javascript Engine

**Comment by ericwlange** [comment]
See issue #64. It should solve your issue.

**Comment by Tlaster** [comment]
I mean create a promise object that actually runs Java code, for example, reading a file from android external storage in javascript.
or can we just ```@jsexport``` a java method and promisify it?

**Comment by ericwlange** [comment]
You can do something like this (not tested, but I've done this before):

```java
JSFunction readFileFromString = new JSFunction(context, "readFileFromString") {
    public JSObject readFileFromString(String fname) {
        JSObject promiseObj = context.evaluateScript(
            "(()=>{" +
            "    let po = {}; po.promise=new Promise((res,rej)=>{po.res=res; po.rej=rej}); return po;"
            "})()");"
         ).toObject();
        final JSFunction resolve = promiseObj.property("res").toFunction();
        final JSFunction reject  = promiseObj.property("rej").toFunction();
        // Spawn off a thread here to do something and call `resolve()` or `reject()` when done
        return promiseObj.property("promise").toObject();
    }
};
```

But I don't know that it will work using raw JavaScript because it needs some sort of environment that periodically runs microtasks.  That's why I suggest using a node `Process` or `MicroService` in issue #64.

**Comment by Tlaster** [comment]
Yeah, it works perfectly, thanks for your help!
