### ISSUE TITLE
Application tag in Mainfest interferes with application Manifest

### ISSUE THREAD

**Issue by baruchn** [LiquidPlayer/LiquidCore#79]
If an Android application is using LiquidCoreAndroid with a configuration of `allowBackup=false` or `supportsRtl=false` it will get an error because of contradicting values in the Manufest of LiquidCore. 
I don't believe that the `<application>` tag is necessary for a library and should probably be removed.

**Comment by ericwlange** [comment]
Agreed -- will remove it.  Thanks for reporting.

**Comment by ericwlange** [comment]
This is fixed in v0.6.0.  The `<application>` tag was added so the instrumentation tests could use HTTP (not HTTPS) for testing.  I moved this to the `androidTest/AndroidManifest.xml`.
