### ISSUE TITLE
Read js file from android asset folder

### ISSUE THREAD

**Issue by akshayd83** [LiquidPlayer/LiquidCore#81]
I am trying to read a js library from asset folder that has multiple functions and I want to call a specific function

,,,
 function verify(string){
   verification logic
}
,,,

  I followed this closed issue to load my .js file https://github.com/LiquidPlayer/LiquidCore/issues/64

  However when I try to read as following it gives me null.

```
   String code = ( ... load javascript here ... );
JSContext context = new Context();
context.evaluateScript(code); // this means passing all java script code
JSFunction jsFoo = context.property("verify").toObject().toFunction();
Boolean isStringValid= jsFoo.call(null, "myString").toboolean;
```
it gives me null any thoughts?

Thanks!

**Comment by ericwlange** [comment]
What exactly are you trying to do with this line?
```
Integer aplus1 = jsFoo.call(null, "myString").toString();
```
and how does it even compile?

It is difficult to know what is failing without knowing the contents of `verify`.  I don't know whether you expect it to return an `Integer` or a `String`, but are you sure it is returning either one?

**Comment by akshayd83** [comment]
Aah sorry my bad.. Essentially i am trying to verify string, so result of function is boolean

**Comment by akshayd83** [comment]
I am able to read the value sucessfully. Actually the java script function was returning an object.

I did as following
```
jsFoo.call(null, "myString").toObject

``

This returned the JSObject and from there I simply used object.property method to read the boolean value.

Thanks again!
