### ISSUE TITLE
How to bind and access nested objects in Android?

### ISSUE THREAD

**Issue by Stephen88** [LiquidPlayer/LiquidCore#84]
Hi,
I am trying to workout how to access nested java objects in javascript.
I have added an example (not complete) below:

public interface Device{
    String getName();
    DeviceProperties getProperties();
}

public interface DeviceProperties {
    int getDeviceType();
    String getDeviceVersion();
}

public class DeviceObject extends JSObject implements Device {
    private DeviceProperties prop;
    public DeviceObject(JSContext ctx) {
        super(ctx, Device.class);
        this.prop = new DeviceProperties(ctx);
    }
    // rest of the impl
}

I am can do a - context.evaluateScript("device.getName()"); 
But how can I do something like device.getProperties.getDeviceType() in JSContext.

**Comment by ericwlange** [comment]
I think you're pretty close, but for simplicity I would use the `@jsexport` attribute rather than the interface.  It's a little cleaner (and I know, not well documented):

```java
public class DeviceProperties extends JSObject {
    public DeviceProperties(JSContext context) {
        super(context);
    }
    @jsexport int getDeviceType() {
        return 12345;  // or whatever
    }
    @jsexport String getDeviceVersion() {
        return "1.23.45"; // or whatever
    }
}

public class Device extends JSObject {
    private final DeviceProperties prop;
    public Device(JSContext context) {
        super(context);
        prop = new DeviceProperties(context);
    }
    @jsexport String getName() { ... }
    @jsexport DeviceProperties getProperties() {
        return prop;
    }
}

```

Both the `Device` and `DeviceType` classes must extend `JSObject` if you want them both to be treated as javascript objects.

Then, in JS:
```javascript
device.getProperties().getDeviceType() === 12345
```

Note that I assume you meant `getProperties()` with the `()` following it.  It is a function.

**Comment by Stephen88** [comment]
Thank you for the quick response. 
I am looking for native engine to run js in android (instead of webview) and the examples provided in AndroidJSCore do give a good starting point.
Sorry about the typo, I was indeed referring to `device.getProperties().getDeviceType();` 
I will try it with annotations as you mentioned. 

Couple of follow-ups:
I guess I can also expose attributes in a similar manner using the annotations?
(May not be the right forum to ask) But curious if JavaScriptCore also supports nested object out of the box?

**Comment by ericwlange** [comment]
Yes, you can expose properties too.  Here's an example from one of my unit tests:

```java
class Foo extends JSObject {
    Foo(JSContext ctx) { super(ctx); }

    @jsexport(type = Integer.class)
    Property<Integer> x;

    @jsexport(type = String.class)
    Property<String>  y;

    @jsexport(attributes = JSPropertyAttributeReadOnly)
    Property<String> read_only;

    @jsexport(attributes = JSPropertyAttributeReadOnly | JSPropertyAttributeDontDelete)
    int incr(int x) {
        return x+1;
    }
}

...

Foo foo = new Foo(ctx);
ctx.property("foo", foo);
ctx.evaluateScript("foo.x = 5; foo.y = 'test';");
assertEquals((Integer)5, foo.x.get());
assertEquals("test", foo.y.get());
foo.x.set(6);
foo.y.set("test2");
assertEquals(6, foo.property("x").toNumber().intValue());
assertEquals("test2", foo.property("y").toString());
assertEquals(6, ctx.evaluateScript("foo.x").toNumber().intValue());
assertEquals("test2", ctx.evaluateScript("foo.y").toString());
ctx.evaluateScript("foo.x = 11");
assertEquals((Integer)11, foo.x.get());
assertEquals(21, ctx.evaluateScript("foo.incr(20)").toNumber().intValue());

foo.read_only.set("Ok!");
assertEquals("Ok!", foo.read_only.get());
foo.read_only.set("Not Ok!");
assertEquals("Ok!", foo.read_only.get());
ctx.evaluateScript("foo.read_only = 'boo';");
assertEquals("Ok!", foo.read_only.get());
```

As for your second question, yes, you can do this in JavaScriptCore, too.  My Swift knowledge is not up to speed yet to be able to quickly write an example, but in Objective-C:

```objective-c
@protocol DevicePropertyExports<JSExport>
- (NSInteger) getDeviceType;
- (NSString*) getDeviceVersion;
@end

@interface DeviceProperty : NSObject<DevicePropertyExports>
@end

@implementation DeviceProperty
- (NSInteger) getDeviceType {
    return 12345;
}
- (NSString*) getDeviceVersion {
    return @"1.23.45";
}
@end

@protocol DeviceExports<JSExport>
- (NSString*) getName;
- (DeviceProperties*) getProperties;
@end

@interface Device : NSObject<DeviceExports>
@property (nonatomic, strong) DeviceProperty *prop;
@end

@implementation Device
- (id) init {
    self = [super init];
    if (self) {
        _prop = [[DeviceProperty alloc] init];
    }
    return self;
}

- (NSString*) getName {
   ...
}

- (DeviceProperties*) getProperties
{
    return self.prop;
}

@end

// Later ...
...
context[@"device"] = [[Device alloc] init];
JSValue *v = [context evaluateScript:@"device.getProperties().getDeviceType()"];
assert(v.numberValue == @(12345));

```

**Comment by Stephen88** [comment]
Hi Eric, Appreciate all the help. I think I now have fair bit of idea on how to proceed. Thank you for the above examples.
