### ISSUE TITLE
LiquidCore base on what v8 version 

### ISSUE THREAD

**Issue by MRwangqi** [LiquidPlayer/LiquidCore#85]
1、I want to know what version of LiquidCore's current v8 is.
2、whether LiquidCore's support ES6?
3、whether LiquidCore's support TypeScript?

**Comment by ericwlange** [comment]
> 1、I want to know what version of LiquidCore's current v8 is.

On Android:
```
> process.versions
{ 
  http_parser: '2.7.0',
  node: '8.9.3',
  v8: '6.1.534.48',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  liquidcore: '0.6.0'
}
```

On iOS, it is not running V8 at all, but JavaScriptCore:
```
> process.versions
{ 
  http_parser: '2.7.0',
  node: '8.9.3',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2o',
  jsc: '8606.2.104.0.1',
  liquidcore: '0.6.0'
}
```

> 2、whether LiquidCore's support ES6?

Yes.

> 3、whether LiquidCore's support TypeScript?

V8 does not directly support TypeScript, but like with anything it can be transpiled to regular javascript.

**Comment by MRwangqi** [comment]
thanks

**Comment by MRwangqi** [comment]
i have a need，Android call JS`s function，Pass the JsonObject to JS
> Android
```
 val obj = JsonObject()
 obj.addProperty("lat", 12.13213231231)
 obj.addProperty("lng", 150.13213231231)
 mJsContext.evaluateScript("changeWayPoint").toFunction().call( null,  obj)
```
> JS segment
```
function changeWayPoint(waypoint) {
   console.log(waypoint)
}
```
I found the  waypoint to be null 

whether LiquidCore not support Android`s Object to JS ? 
whether LiquidCore only support Basic type？eg:(String,Int ...)

**Comment by ericwlange** [comment]
LiquidCore does not support `JsonObject`, but that is a good idea.  But LiquidCore does provide `JSObject`, which does essentially the same thing:

```kotlin
val obj = JSObject(mJSContext)
obj.property("lat", 12.13213231231)
obj.property("lng", 150.13213231231)
mJsContext.evaluateScript("changeWayPoint").toFunction().call( null,  obj)
```

**Comment by MRwangqi** [comment]
Looks like LiquiCore does not support releasing JSContext

**Comment by ericwlange** [comment]
What do you mean?  It will release when it is garbage collected. Just don't hold a reference to it when you're done.

**Comment by consp1racy** [comment]
@MRwangqi What's `JsonObject`? Please point me to a javadoc page. The API is totally different from Android's `JSONObject` (but the addition is appreciated).
