### ISSUE TITLE
how to support 'require' and 'exports' without MicroService

### ISSUE THREAD

**Issue by LightSun** [LiquidPlayer/LiquidCore#87]

**Comment by ericwlange** [comment]
It depends on what you are trying to do. But for pure JS, you can use
`liquidcore-cli` to bundle your JS into a single file and load that file:

```
npm run bundler -- --platform=android
```
will start with `liquid.js` (you can change that with a command line
option) and bundle all required modules into a single file called
`liquid.bundle`. You can then load that as an asset and run it without a
micro service.

**Comment by LightSun** [comment]
i just want load another js module from local.

**Comment by ericwlange** [comment]
You can only use `require` with the bundler.

**Comment by LightSun** [comment]
bundler ?Can you tell me in detail?

**Comment by ericwlange** [comment]
```
npm install -g liquidcore-cli
liquidcore init myProject
cd myProject && npm install
```

Change `index.js` to be whatever you want it to be.  You can `require` anything you want (so long as it is pure javascript -- if you are not using a microservice, you can't use built-in node modules).

Then,

```
npm bundler -- --platform=android
```

Now you have a file called `liquidcore.bundle`.  This is a single, bundled version of all of your modules, starting with whatever you put in `index.js`.

In Android, drop that file in your assets folder and load it into a string (`myJSCodeString`).

Then,

```java
JSContext context = new JSContext();
context.evaluateScript(myJSCodeString);
```

**Comment by LightSun** [comment]
ok. even if this not support 'require'. I still want to thank you.
