### ISSUE TITLE
Stop JSContext

### ISSUE THREAD

**Issue by TebbeUbben** [LiquidPlayer/LiquidCore#89]
Is there a way to stop the execution of JSContext from another thread after calling evaluateScript?

**Comment by ericwlange** [comment]
Not in the default API, no.  There is no interrupt mechanism exposed.  It is, however, possible to do in JNI.  See issue #65.

I'm curious, though, as this is not the first time this question has been asked.  What is the scenario in which you need this?  JavaScript is designed to run in short bursts in a single thread.  Why do you have code that can get stuck?  This seems more like a bug than a feature.

**Comment by TebbeUbben** [comment]
Basically it is a script that analyzes data. The execution times can vary between a few seconds and several minutes - based on how much data you want it to process.
So it is not a big, it is doing what it is supposed to, but it would be nice to stop the script if the user decides to cancel that operation.

**Comment by ericwlange** [comment]
Ok, so it is not stuck in an endless loop.  It would eventually exit, but you don't want to wait for it.  Got it.  I ask because I am debating whether it is a common enough use case to warrant exposing a method in the API.

**Comment by TebbeUbben** [comment]
I really would appreciate it!

**Comment by bangonkali** [comment]
this is highly appreciated. it might be odd but one of my use case is to run short burst js code coming from the database. but sometimes the js code could be coded poorly by the user so i would like to be able to watch the runtime, if exceeds a certain timeout, then stop the code, and moves on to the next row in the database.

**Comment by ericwlange** [comment]
This feature now exists in 0.6.1.  See:

[`JSContextGroup.terminateExecution()`](https://liquidplayer.github.io/LiquidCoreAndroid/0.6.1/org/liquidplayer/javascript/JSContextGroup.html#terminateExecution).
