### ISSUE TITLE
[ANDROID]: require('...') java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by AinisSK** [LiquidPlayer/LiquidCore#93]
Hi, I'm a little bit confused, do we need metro bundler or we can do everything in an Android app. I'm using LiquidCore on Android and set up MicroService like that:

> val service = MicroService(
                this,
                URI("android.resource://my.package.name/raw/liquid?platform=android&dev=true"),
                MicroService.ServiceStartListener { }
            )
service.start()

I faced the following issue:

- When I try to create MicroService with URL to `android.resource://...liquid.js...` `InvocationTargetException require('./index')` is thrown.
- If I target MicroService directly to `index.js` 'PingPong' sample works great, BUT if I install some additional modules and add `require('...')` to `index.js` the same exception is being thrown.

The main idea is to run NodeJs app on Android and interact with it. So, how to make MicroService understand ‘require’ and build all dependencies? Should I put something else into android raw directory?

**Comment by ericwlange** [comment]
When you use a local resource, the arguments (`?platform=android&dev=true`) are not necessary.  Not sure if that is causing a problem, but just a note.

To use a resource bundle, you actually have to bundle it.  You can run:

```
npm run bundler -- --platform=android
```

This will generate a file called `liquid.bundle`.  Copy this to your raw resource folder and rename it to `liquid.js` or `liquid.bundle.js` and then your URI would be `android.resource://my.package.name/raw/liquid` or `android.resource://my.package.name/raw/liquid.bundle`, respectively.

LiquidCore does not dynamically load modules that are required using `require`.  Instead, it expects all js files to be bundled into a single file.  When you run `npm run server`, it is generating a bundle each time a request is made.  `npm run bundler` will generate a one-time bundle that you can use as a resource.

**Comment by AinisSK** [comment]
Thank you a lot, I was getting an error during bundler execution and I forgot about this step. Now I solved that error and everything works fine)
